package response

// Collection of status.
const (
	StatOK                                string = "OK"
	StatCreated                           string = "CREATED"
	StatUpdated                           string = "UPDATED"
	StatNotFound                          string = "NOT_FOUND"
	StatUnexpectedError                   string = "UNEXPECTED_ERROR"
	StatInsufficientPoint                 string = "INSUFFICIENT_POINT"
	StatusInvalidPayload                  string = "INVALID_PAYLOAD"
	StatUnauthorized                      string = "UNAUTHORIZED"
	StatAlreadyExist                      string = "ALREADY_EXIST"
	StatBadRequest                        string = "BAD_REQUEST"
	StatDuplicateNationalityID            string = "DUPLICATED_NATIONALITY_ID"
	StatDuplicateClaim                    string = "DUPLICATE_CLAIM"
	StatDuplicateRegistrationNumber       string = "DUPLICATED_REGISTRATION_NUMBER"
	StatInvalidUserSession                string = "INVALID_USER_SESSION"
	StatNotImplemented                    string = "NOT_IMPLEMENTED"
	StatForbidden                         string = "FORBIDDEN"
	StatRequestTimeout                    string = "REQUEST_TIMEOUT"
	StatSubsidyClaimIsInPeriod            string = "SUBSIDY_CLAIM_IS_IN_PERIOD"
	StatDuplicateEmail                    string = "DUPLICATED_EMAIL"
	StatDuplicateGasStationNumber         string = "DUPLICATED_NUMBER"
	StatInvalidAdminRole                  string = "INVALID_ADMIN_ROLE"
	StatNotPermitted                      string = "NOT_PERMITTED"
	StatOldNewPasswordSame                string = "OLD_NEW_PASSWORD_SAME"
	StatInvalidUserPassword               string = "INVALID_USER_PASSWORD"
	StatExpiredOTPCode                    string = "OTP_CODE_EXPIRED"
	StatInvalidLoginSession               string = "INVALID_LOGIN_SESSION"
	StatOnVerification                    string = "UNIT_ON_VERIFICATION"
	StatInactivatedSpbu                   string = "INACTIVATED_SPBU"
	StatInactivatedEmail                  string = "INACTIVATED_EMAIL"
	StatWaitingForVerification            string = "WAITING_FOR_VERIFICATION"
	StatCounterSubmissionNotYetExpired    string = "COUNTER_SUBMITTER_NOT_YET_EXPIRED"
	StatCounterSubmissionExpiredNotSet    string = "COUNTER_SUBMITTER_EXPIRED_NOT_SET"
	StatCounterSubmissionNotFound         string = "COUNTER_SUBMITTER_NOT_FOUND"
	StatDisputeNationaliyNotClosed        string = "DISPUTE_NATIONALITY_NOT_CLOSED"
	StatDisputeNationaliyAlreadyClosed    string = "DISPUTE_NATIONALITY_ALREADY_CLOSED"
	StatDisputeLicenseNumberNotClosed     string = "DISPUTE_LICENSE_NUMBER_NOT_CLOSED"
	StatDisputeLicenseNumberAlreadyClosed string = "DISPUTE_LICENSE_NUMBER_ALREADY_CLOSED"
	StatMaxResetQRExceeded                string = "MAX_RESET_QR_EXCEEDED"
	StatActionHasBeenTaken                string = "ACTION_HAS_BEEN_TAKEN"
	StatResetPasswordRequestExceed        string = "RESET_PASSWORD_USER_EXCEED"
	StatUnitNotVerified                   string = "UNIT_NOT_VERIFIED"
)
